Update baseviews.py
dpgaspar/Flask-AppBuilder pull request #1517
Opened 2020-11-11 10:32 UTC by runoutnow

The f-string was wrong

### Description

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Is CRUD MVC related.
- [ ] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

2020-11-12 14:21 UTC, dpgaspar commented
Nice, thks, just a lint problem:
```
flask_appbuilder/baseviews.py:258:91: E501 line too long (93 > 90 characters)
```

2020-11-12 15:23 UTC, runoutnow commented
> Nice, thks, just a lint problem:
> 
> ```
> flask_appbuilder/baseviews.py:258:91: E501 line too long (93 > 90 characters)
> ```

ah I thought why use two f-strings for this if you can use one... but that's why =)

2020-11-13 11:17 UTC, runoutnow commented
Sorry for the mess in this topic.
I want to make another pull request, but that file is now on this topic...

the changed file for the new pull request doesn't show up when I click "new pull request".

2021-01-04 15:18 UTC, dpgaspar requested changes
LGTM, but please remove the retry on the `get_user_by_id`

2021-01-04 15:18 UTC, dpgaspar commented on flask_appbuilder/security/sqla/manager.py
> +        try:
This seems some sort of retry. What problem are you experiencing?

2021-01-31 06:25 UTC, runoutnow reviewed
> LGTM, but please remove the retry on the `get_user_by_id`

Weeks ago I have removed the retry, but it seems that this pull request is stuck on “change required” while there’s nothing left to change. Perhaps because I previously deleted the file. So I have put a comment in manager.py, merged it and then removed the comment and merged it again. Perhaps github will now determine that the retry on `get_user_by_id` has been removed.

2021-02-09 19:51 UTC, closed without merging